---
- name: Install nginx
  hosts: hw1
  become: true

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  - name: Download hw0 from git
    command: git clone https://github.com/derekwang117/CSE-356.git

  - name: Insert Index Page
    command: mv CSE-356/hw0.html /var/www/html

  - name: Insert Image Page
    command: mv CSE-356/ruble.PNG /var/www/html

  - name: Edit nginx default
    replace:
      path: /etc/nginx/sites-available/default
      regexp: 'index.nginx-debian.html'
      replace: 'hw0.html'

  - name: Restart NGiNX
    service:
      name: nginx
      state: restarted

# for docker, mkdir nginx-html with index.html, then do docker run -d -p 8080:80 -v ~/nginx-html:/usr/share/nginx/html nginx
